name: gitartwork from a contribution graph

on:
  push:
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate gitartwork SVG
        uses: jasineri/gitartwork@v1
        with:
          user_name: kanksha44
          text: kanksha

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update gitartwork SVG"
          git push
